program:
  programName: Test
  maxThreadRestartCount: 3

queue:
  preProcess:
    threadCount: 5
  connect:
    - threadName: Test_1
      host: 8.8.8.8
      user: test1
      password: test123
      queuePath: /QSYS.LIB/test.LIB/test.DTAQ
      dataGroup: TEST
      maxWaitTime: 60
      maxRetryCount: 3
      maxIdleHeartbeat: 5
      ackMode: true
      messageProcessorThreadCount: 1








